fix: switch to downloading from Filecoin Saturn
libp2p/npm-go-libp2p pull request #2
Opened 2023-02-06 20:35 UTC by achingbrain

[Filecoin Saturn](https://strn.network/)'s http gateway is like ipfs.io, just with caching so it should prevent the [intermittant CI failures](https://github.com/libp2p/js-libp2p/actions/runs/4105171858/jobs/7081659680) we sometimes see.

2023-02-07 00:22 UTC, lidel approved these changes
Fine as a quick fix, but long term, we should not use anything other than `ipfs.io` unless we switch to CAR and do hash verification. Using `?format=car` will allow us having multiple fallbacks like cloudflare, saturn, and ipfs.io.

Right now,  iirc, `strn.pl` points back at `ipfs.io` for requests other than raw block or CAR :upside_down_face: So this PR still uses `ipfs.io`, only adds 1 layer cache.

But in the future, Saturn may decide (or misconfigure something) to do deserialization directly on these random nodes run by random people, and at that point someone could join Saturn, and return malicious block for executable, instead of correct one, and  MITM our infra, leak secrets (if we are not doing CARs).

2023-02-17 01:45 UTC, lidel requested changes
# :warning: 

@achingbrain confirmed we should not do this: these are third-party nodes that could return malicious payload. Only thing that is safe to be fetched from strn.pl are [verifiable CARs and blocks for specific CIDs](https://docs.ipfs.tech/reference/http/gateway/#trustless-verifiable-retrieval)

2023-02-21 13:06 UTC, achingbrain commented
Having closed this, I notice we do actually [check that we can create a CID from the downloaded file](https://github.com/libp2p/npm-go-libp2p/blob/master/src/download.js#L57) that matches the one we requested so I think we are ok on that front.

2023-03-09 07:08 UTC, achingbrain commented
Nudge @lidel

2023-03-09 07:22 UTC, achingbrain commented
Alternative: https://github.com/libp2p/npm-go-libp2p/pull/7

2023-03-14 13:03 UTC, lidel commented
Let's do  https://github.com/libp2p/npm-go-libp2p/pull/7#pullrequestreview-1339223009 instead (mind closing this one?)

2023-03-14 13:04 UTC, closed without merging